import { create } from 'zustand'
import type { User } from '../../../shared/types/domain'
import {
  clearStoredRefreshToken,
  loadStoredRefreshToken,
  saveStoredRefreshToken,
} from '../services/session-storage'

interface SessionState {
  accessToken: string | null
  refreshToken: string | null
  user: User | null
  isAuthenticated: boolean
  isBootstrapped: boolean
  setSession: (input: {
    accessToken: string
    refreshToken: string
    user: User
  }) => Promise<void>
  setUser: (user: User) => void
  updateTokens: (input: { accessToken: string; refreshToken: string }) => void
  clearSession: () => Promise<void>
  bootstrap: () => Promise<void>
}

export const useSessionStore = create<SessionState>((set) => ({
  accessToken: null,
  refreshToken: null,
  user: null,
  isAuthenticated: false,
  isBootstrapped: false,

  setSession: async ({ accessToken, refreshToken, user }) => {
    set({
      accessToken,
      refreshToken,
      user,
      isAuthenticated: true,
    })
    await saveStoredRefreshToken(refreshToken)
  },

  setUser: (user) => {
    set({ user })
  },

  updateTokens: ({ accessToken, refreshToken }) => {
    set({ accessToken, refreshToken })
  },

  clearSession: async () => {
    set({
      accessToken: null,
      refreshToken: null,
      user: null,
      isAuthenticated: false,
    })
    await clearStoredRefreshToken()
  },

  bootstrap: async () => {
    const refreshToken = await loadStoredRefreshToken()
    if (refreshToken) {
      // Only refresh is persisted. Access token will be regenerated by
      // the HttpClient on the first 401 (or by an explicit /me probe).
      set({
        refreshToken,
        isBootstrapped: true,
      })
      return
    }
    set({ isBootstrapped: true })
  },
}))

export function getAccessToken() {
  return useSessionStore.getState().accessToken
}
